//
//  AppImage.swift
//  mood-recorder
//
//  Created by LanNTH on 02/08/2021.
//

import SwiftUI

enum AppImage: Int, CaseIterable {    
    case bodyOil
    case bra
    case brush1
    case brush2
    case brush
    case candle
    case comb1
    case comb
    case corset
    case cream
    case dress2
    case dressingTable
    case dryer
    case dye
    case earing
    case eyeShadow
    case eyeShadows
    case facialMask
    case fragance
    case hairBrush
    case hairIron
    case hairSalon
    case handMirror
    case handbag
    case lips
    case lipstick
    case lotion
    case lotus
    case mascara1
    case mascara
    case mirror1
    case mirror
    case nail
    case nailPolish1
    case nailPolish
    case nail1
    case necklace1
    case panties
    case powder
    case rollOn
    case serum
    case shampoo
    case soapBeauty
    case spa
    case spray
    case sunCream
    case tint
    case tissues
    case weighLoss
    case woman
    case basket1
    case basket
    case bottle1
    case bottle2
    case bottle3
    case bottle4
    case bottle5
    case bottle6
    case bottle7
    case broom1
    case broom2
    case bubbles2
    case bucket
    case bucket1
    case bucket2
    case detergent
    case dishWashing1
    case houseCleaning
    case paperTowel
    case rake
    case rubbishBin1
    case rubbishBin2
    case rubbishBin3
    case rubbishBin
    case sink
    case soap1
    case soap2
    case soap3
    case softener
    case spray1
    case spray2
    case wash
    case washingMachine
    case washingUp
    case wc
    case wetFloor
    case wheel
    case windowCleaning1
    case windowCleaning2
    case bubbles1
    case angelDino
    case angry
    case angryRawr
    case artist
    case beauty
    case beauty1
    case beauty2
    case birthday
    case boxing
    case chefDino
    case coolDino
    case costume
    case dancingDino
    case devilDino
    case dinoCrying
    case dinoInlove
    case dinoShower
    case dizzy
    case doctorDino
    case drawingDino
    case drink
    case drunkDino
    case eat
    case embarrassed
    case exerciseDino
    case fear
    case ghostDino
    case happyDino
    case ideaDino
    case kiss
    case laughingDino
    case movie
    case music
    case painter
    case phoneCall
    case photographer
    case readingDino
    case scientist
    case selfieDino
    case sickDino
    case sing
    case sleepyDino
    case space
    case stanClaus
    case surprise
    case swim
    case thief
    case think
    case warm
    case workerDino
    case alarmClock
    case atom
    case backpack
    case binder
    case blackboard
    case books
    case briefcase
    case calculator
    case colorPalette
    case compass
    case deskChair
    case desk
    case deskLamp
    case dictionary
    case diploma
    case dna
    case easel
    case examFail
    case exam
    case field
    case flask
    case flute
    case folder
    case fountainPen
    case geography
    case glasses
    case hightlighter
    case laptop
    case lockers
    case medal
    case microscopeStudy
    case mortarboard
    case notebook
    case notebookOpen
    case paperPlane
    case pen
    case pencilCase2
    case pencilCase
    case ruler
    case schoolBus
    case school
    case sculpture
    case solarSystem
    case studentCard
    case telescope
    case testing
    case timeTable
    case trophy
    case whistle
    case whiteboard
    case airhorn
    case auditorium
    case balloons
    case banner
    case beach
    case cakeParty
    case candy
    case champagne
    case clown
    case confetti
    case cupcake
    case cups
    case date
    case dinnerTable
    case discoBall
    case dress
    case eventHall
    case eyeMask
    case fireworks
    case garlands
    case giftBox
    case gong
    case highHeels
    case host
    case icCard
    case invitation
    case kazoo
    case location
    case magicShow
    case microphone
    case openingCeremony
    case partyBlower
    case partyHat
    case photoBooth
    case photoCamera
    case pinata
    case pizzaParty
    case poolParty
    case redCarpet
    case saxophone
    case skewer
    case speaker
    case stage
    case suit
    case theater
    case ticket
    case videoCamera
    case vinylPlayer
    case waiter
    case weddingArch
    case alcohol
    case apple
    case avocado
    case bacon
    case banana
    case bbq
    case beer
    case blueberry
    case boiledEgg
    case breadOvan
    case breakfast
    case butter
    case cake
    case carrot
    case casserole
    case celery
    case cheese
    case chicken
    case chocolateBar
    case cocktail
    case coffeeCup
    case corn
    case croissant
    case cucumber
    case cutlery
    case cutlet
    case dessert
    case doughRollingaction
    case dumpling
    case eggplant
    case eggs
    case fastFood
    case fish
    case flour
    case frenchFries
    case garlic
    case glutenFree
    case grape
    case groceries
    case ham
    case healtyFood
    case honey
    case hotDog
    case iceCream
    case jam
    case juice
    case kebab
    case kiwi
    case lemon
    case lettuce
    case milk
    case milkshake
    case muffins
    case mushroom
    case nuts
    case octupus
    case oliveOil
    case omelette
    case orange
    case pancake
    case peanutButter
    case peas
    case pepper
    case pieceOfcake
    case pillowBread
    case pineapple
    case pizza
    case pizzaSlice
    case plate
    case pork
    case porridge
    case poultry
    case pumpkin
    case rice
    case roastChicken
    case saladDisk
    case salad
    case salmon
    case saltAndpepper
    case sandwich
    case sauce
    case sausage
    case shrimp
    case smoothie
    case soup
    case spagetti
    case squid
    case steak
    case strawberry
    case sushiFish
    case sushi
    case sushuRoll
    case taco
    case tea
    case tomato
    case tray
    case vegetable
    case waterBottle
    case wine
    case yogurt
    case actionCamera
    case baking
    case barbecue
    case basketball
    case bonsai
    case bowling
    case buildingPlan
    case cactus
    case chatChit
    case chess
    case cinema
    case coffeeHobby
    case controller
    case cookingPod
    case domino
    case doughRolling
    case exercise
    case facialMaskhobby
    case fishing
    case gardening
    case guitar
    case headphone
    case instantCamera
    case jogging
    case karaoke
    case kayak
    case laptopAndbook
    case newspaper
    case origami
    case petCare
    case piano
    case pingPong
    case plant
    case playingCard
    case postStamp
    case readingBook
    case sewing
    case shopping
    case skateboard
    case smartphonePlay
    case soccerBall
    case socialCamera
    case surfboard
    case swimming
    case teaHobby
    case telescopeHobby
    case tvScreen
    case vrGlasses
    case worker
    case yoga
    case accesibility
    case accomodation
    case accountant
    case ads
    case assignment
    case b2b
    case blogger
    case brief
    case budget
    case business
    case cashFlow
    case coding
    case coffeeJobs
    case consultant
    case content
    case contentWriting
    case customer
    case designer
    case digitalNomad
    case digitalNomad1
    case editor
    case exchange
    case finance
    case growth
    case heathycare
    case income
    case influencer
    case invoice
    case laundry
    case mail
    case marketing
    case network
    case onlineShop
    case opportunity
    case passionate
    case passport
    case pos
    case productivity
    case research
    case sleep
    case socialMedia
    case startup
    case timeManagenment
    case toDolist
    case translator
    case travel
    case vlog
    case vlogger
    case webDesign
    case brokenHeart
    case diamondRing
    case fireLove
    case gift
    case heart
    case inLove
    case lesbian
    case longDistance
    case loveBear
    case loveBed
    case loveBird
    case loveChem
    case loveChocolate
    case loveDiary
    case loveFly
    case loveForever
    case loveFrame
    case loveGay
    case loveHouse
    case loveLetter2
    case loveLetter
    case loveNight
    case lovePhoto
    case lovePill
    case loveTexting
    case loveYinyang
    case roses
    case valentine
    case weddingRing
    case wineGlass
    case bacteria
    case bloodCells
    case bloodPressuregauge
    case bloodTest
    case bodyScale
    case bones
    case cervicalCancer
    case colesterol
    case defribillator
    case dental
    case diabetes
    case diet
    case doctor
    case dumbbell
    case ear
    case ekg
    case eyeExamination
    case faceMask
    case healthInsurance
    case heartRate
    case hospital
    case kidney
    case liver
    case lungs
    case medicalApp
    case medicalAppointment
    case medicalCheckup
    case medicalFolder
    case medicalLocation
    case medicalReport
    case medicalReportpaper
    case medicine
    case mentalHealth
    case microscope
    case mobilePhone
    case monitor
    case noSmoking
    case nurse
    case phoneCallmedical
    case prescription
    case question
    case smartWatch
    case sonography
    case speechBubble
    case stethoscope
    case urineTest
    case vaccine
    case virus
    case waterBottleandcup
    case xRays
    case angel
    case angryPineapple
    case astronaut
    case birthdayPineapple
    case blushing
    case bubblesPineapple
    case calling
    case chef
    case coffee
    case confuse
    case cool
    case crying
    case dancing
    case detective
    case devil
    case drawing
    case drunk
    case eating
    case exercisePineapple
    case facial_treatment
    case ghost
    case happy
    case hot
    case idea
    case laptopPineapple
    case laughing
    case listening
    case love
    case pirate
    case popsicle
    case reading
    case sad
    case scare
    case scientific
    case selfie
    case shower
    case sick
    case singing
    case sleeping
    case strong
    case sunbathing
    case superhero
    case surfing
    case surprised
    case thinking
    case toothbrushing
    case volleyball
    case whistlePineapple
    case wrestler
    case zombie
    case bigWind
    case calendarSun
    case cellphoneForecast
    case cloudyDay
    case cloudyNight
    case cloudyWind
    case cold
    case crescentMoon
    case cyclone
    case drop
    case dropSingle
    case earth
    case earthSun
    case eclipse
    case flowerFlying
    case flowerSingle
    case fullMoon
    case heavyRain
    case heavySnow
    case heavyStorm
    case heavyThunder
    case leafFalling
    case leafRedhappy
    case mountain
    case newMoon
    case rain
    case rainNight
    case rainbow
    case regularRainy
    case regularSnow
    case snow
    case snowflake
    case snowman
    case springRain
    case sunny
    case sweat
    case thermometerCold
    case thermometerHot
    case thermometer
    case thunder
    case tornado
    case treeFalling
    case treeHappy
    case treeRedhappy
    case umbrellaColorful
    case umbrella
    case umbrellaNormal
    case waxingMoon
    case wildFire
    case wind
}
